<?php
// generated by Poedit from ictuwp-plugin-rijkshuisstijlposttypes-en_GB.po, do not edit directly
return ['domain'=>NULL,'plural-forms'=>'nplurals=2; plural=(n != 1);','language'=>'en_GB','pot-creation-date'=>'2026-04-29 12:26+0200','po-revision-date'=>'2026-04-29 12:26+0200','translation-revision-date'=>'2026-04-29 12:26+0200','project-id-version'=>'ICTU / WP / DO - Register post types and taxonomies','x-generator'=>'Poedit 3.9','messages'=>[]];
