<?php
// generated by Poedit from ictuwp-plugin-rijkshuisstijlposttypes-en_US.po, do not edit directly
return ['domain'=>NULL,'plural-forms'=>'nplurals=2; plural=(n != 1);','language'=>'en_US','pot-creation-date'=>'2025-12-18 14:23+0100','po-revision-date'=>'2025-12-18 14:23+0100','translation-revision-date'=>'2025-12-18 14:23+0100','project-id-version'=>'ICTU / WP / DO Register post types and taxonomies','x-generator'=>'Poedit 3.8','messages'=>[]];
